tab4 <- tabPanel(
  "Summary takeaways",
  p("After completing the research and analyzing all the data, the three major takeaways we have come up with are; alcohol does negatively impact students final grades, alcohol affects different peoples health differently, and male students who are heavy consumers of alcohol see drastic drops in their class grades. To start, we have learned that when looking at students aged 18-22 we see a big shift in alcohol consumption levels and the effects they have on class failure. Looking at both genders, at 18, students who were consuming low levels of alcohol were doing fairly well in school and those who were consuming high levels of alcohol were only failing a low percentage of classes. On the other hand after the age of 20 and onwards, the percentages started to equal and even flip to the point where we see students with high alcohol consumption levels failing at an average percentage close to 100%."), 
  p("With the second takeaway being the affects of alcohol on students health, we come to realize that there are a lot more factors than just alcohol that affects students health. Many people have underlying health conditions or issues that they might not be aware of affecting their health negatively on top of whatever their alcohol consumption level is. From our study we tend to see that with the group of students who consume alcohol at a low levels their health conditions are fairly even and lean more towards very good health. A surprise for us was to see that the group of students that consumed very high levels of alcohol were either of very average health condition or very bad."),
  p("The third point we can takeaway from our research is that when looking at the group of male students who consumed alcohol at high to very high levels, they tend to perform very poorly compared to their female counterparts. A surprise to us in our research was to see that in some cases females who drank a lot of alcohol received better grades then females who did not drink a lot of alcohol. These results do all have to be looked at with a little bit of judgement and given a small margin of uncertainty due to the fact that different students consider different amounts to be equivalent to different levels of alcohol consumption. ")
)



